default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: my_door_lock_development
  username: dev
  password: password

test:
  <<: *default
  database: my_door_lock_test
  username: test
  password: password

production:
  <<: *default
  password: <%= ENV['DATABASE_URL'] %>
